<?php
    $clanky = Db::queryAll("SELECT * FROM zpravy ORDER BY id DESC");
    $i = 0;
?>

<style>
    .first-news{
        height: calc(100vh - 106px)!important;
        background-size: cover!important;
        position: relative;
        background-position: center center!important;
        color: #fff!important;
    }
    .first-news h2{
        position: relative;
        z-index: 10;
    }

    .text-first-news{
        position: relative;
        bottom: 0;
        z-index: 10;

    }

    .first-news::after{
        position: absolute;
        width: 100%;
        height: 100%;
        left: 0;
        top: 0;
        content: '';
        background: rgba(0,0,0,0.5);
    }

    .image_homepage{
        width: 100%;
    }

</style>


<div class="first-news" style="background: url(<?="../img/".$clanky[0]['obrazek1']?>) no-repeat; ">
    <div class="container">
        <h2><?= $clanky[0]['nadpis'] ?></h2>
    </div>
    <div class="container text-first-news">
        <p><?= $clanky[0]['text1'] ?></p>
    </div>
</div>




<div class="container">
    <?php foreach ($clanky as $item): ?>
        <?php if($i>0):?>
            <div class="zprava-vypis">
                <h2><?= $item['nadpis'] ?></h2>
                <div class="row">
                    <div class="col-md-6">
                        <p><?= $item['text1']?></p>
                    </div>
                    <div class="col-md-6">
                        <img src="../img/<?=$item['obrazek1']?>" class="image_homepage" ></img>
                    </div>
                </div>

            </div>
        <?php endif;?>
      <?php $i++ ?>
    <?php endforeach; ?>
</div>
