<div class="container-fluid">
    <div class=" fixed info-right">
        <div class="all-right">
            <div class="up-right">
                <h1>Vítejte</h1>
            </div>
            <div class="login-div">
                <form class="" method="post">
                    <legend>Přihlášení</legend>
                    <input type="text" name="jmeno" placeholder="Jméno"><br>
                    <input type="password" name="heslo" placeholder="Heslo"><br>
                    <input type="submit" name="odeslat" value="Přihlásit" >
                </form>
                
            </div>
        </div>
    </div>
</div>